### ISSUE TITLE
Custom SSH port

### ISSUE THREAD

**Issue by Thlb** [os-js/osjs-xterm-application#11]
Hi,

Is there a way to set a specific port for ssh (instead of default 22) ?

Adding in : src/server/config.js, "port: 12345"

Thanks

**Comment by andersevenrud** [comment]
Hi,

This is currently not possible, but I'm adding this functionality as we speak :)

**Comment by andersevenrud** [comment]
If you run `npm update @osjs/xterm-application` it is now possible to change the SSH connection options etc.

See the new section added in the readme here: https://github.com/os-js/osjs-xterm-application#usage

**Comment by Thlb** [comment]
Working like a charm !

Thanks !

**Comment by andersevenrud** [comment]
Great! No problem :)
