### ISSUE TITLE
dependency node-pty does not compile on node v13.5.0 armv7l

### ISSUE THREAD

**Issue by erfan-azhdari** [os-js/osjs-xterm-application#12]
the latest node-pty version fixed this issue please update the app to use the latest version

**Comment by andersevenrud** [comment]
I published version `1.1.15` with upgraded node-pty.

Let me know if it works out :)

**Comment by erfan-azhdari** [comment]
It works now thanks.
Closing the issue.

**Comment by andersevenrud** [comment]
Glad to hear it :)
