### ISSUE TITLE
xterm crashes when I press space !

### ISSUE THREAD

**Issue by msjavan** [os-js/osjs-xterm-application#13]
when I press space, the app freezes and not works any more.

**Comment by andersevenrud** [comment]
Thanks. I'll look at it asap!

**Comment by andersevenrud** [comment]
I cannot reproduce this in my environment.

Could you please take a screenshot or video of what happens, as well as the server logs ?

Also, check the browser developer console for errors.

**Comment by msjavan** [comment]
you can check it at my live deployment. can you remember the address ?

**Comment by andersevenrud** [comment]
No, I don't remember that. Also, you should not share this if it's on a private server not meant for the public. You can send me an email with the link.

**Comment by msjavan** [comment]
Not that much important, It is on test. I send it privately @ gitter

**Comment by msjavan** [comment]
change the locale to persian and test the xterm

**Comment by andersevenrud** [comment]
So it is locale dependent if this happens or not ?

**Comment by msjavan** [comment]
I'm not sure! I changed os-js locale, but I'm writing english on xterm

**Comment by andersevenrud** [comment]
So why should I change to persian then ?

**Comment by msjavan** [comment]
you are right.

**Comment by andersevenrud** [comment]
I am right as in it's not needed, or I have to change to persian ?

**Comment by msjavan** [comment]
The problem is locale dependent (just I see it in persian, not other languages), may be its related to rtl

**Comment by andersevenrud** [comment]
Thanks. I'll look into it asap.

**Comment by msjavan** [comment]
I send some screenshots at gitter

**Comment by andersevenrud** [comment]
I can confirm that RTL is the cause of this. On an LTR system a space sends the `[1C` sequence, while on RTL it sends a ` [27D` which causes something to go very wrong.

I see that I'm a bit behind on the xterm and pty dependencies, so I'll try updating these. I see there's some breaking changes, so I have to approach this a bit carefully.

I'll let you know about my findings ASAP.

**Comment by andersevenrud** [comment]
I tried updating everything, but still the same problem (although the actual keycode now seems to be fixed).

So I tried to reproduce this outside OS.js, and I found an issue in xterm itself.

I've reported this bug upstream so I'll report back when I know more :smile:

**Comment by andersevenrud** [comment]
I've added a possible workaround for this. Could you please test the following : 

```
npm install --save @osjs/xterm-application@experimental
```

**Comment by msjavan** [comment]
Thanks a lot, Its working !

**Comment by andersevenrud** [comment]
Glad to hear it! I'll publish this as a proper version if you don't find any more issues with it :)

**Comment by andersevenrud** [comment]
I've published this version onto npm
