### ISSUE TITLE
Websocket Keepalive

### ISSUE THREAD

**Issue by elixx** [os-js/osjs-xterm-application#17]
Thanks so much for your quick response. This is an amazing project, and I hope to do a lot with it :) The potential is amazing! I hope to contribute in the future, but am somewhat green to Javascript. Been learning a lot about browser nuances!

When running an Xterm through CloudFlare, it disconnects after a period of idle time:
![image](https://user-images.githubusercontent.com/2325870/83179460-1568b400-a0f0-11ea-84b5-c0b4023b6975.png)

I experienced a similar issue with the core until it was resolved with the fix to https://github.com/os-js/osjs-server/issues/30 

Could we have a similar ping option for Xterm?

**Comment by andersevenrud** [comment]
I think I have a pretty good solution for this here: https://github.com/os-js/osjs-xterm-application/pull/18

It involves overriding the standard communication with Xterm, making everything a JSON object so that it's possible to specify if the messages are for I/O or something else -- in this case ping.

Just curious before I merge this, how long of a ping interval do you think you need ?

I've set it to 30s atm.

**Comment by andersevenrud** [comment]
> I think I have a pretty good solution for this here: #18

And I'm pushing something a bit less hackish now, heh.

**Comment by elixx** [comment]
Interesting -- I think 30 or 45 would be fine.

For the core, [I think that] I overload the ping interval with the following in `src/server/config.js`:
```
  ws: {
    ping: 7200
  }
```

I don't know if it actually works, or not, but a similar configurable method is a thought.

**Comment by andersevenrud** [comment]
Okay. I've pushed another commit that allows for overriding this in `src/client/config.js`:

```
{
  xterm: {
    ping: 30000
  }
}
```

So if all of this sounds fine, I can probably push this out ASAP :)

**Comment by elixx** [comment]
I tried to pull in the latest. but am now getting `Package Loading 'Xterm' failed: /apps/Xterm/main.js, /apps/Xterm/main.css`.
What is the proper method? I tried a few things, so far..

**Comment by andersevenrud** [comment]
> I can probably push this out ASAP :)

I mean *publish* it :blush:

**Comment by elixx** [comment]
Sure! I'm giving it a shot...
I figured out how to pull it in with the git version ;)

**Comment by andersevenrud** [comment]
> I figured out how to pull it in with the git version ;)

Oh yeah ? Let me know how that works out. Would be nice to have a tester outside me before I merge these changes.

If you open the devtools before launching the app, and then go to the `Network` tab and find the socket created by the app you should see a "ping" message go out on the set interval.

If you can confirm that, as well as everything is working as it should that would put me at ease, hehe :)

**Comment by elixx** [comment]
No problem! Happy to help test anything -- I'm getting somewhat comfortable.

I uninstalled the NPM version and added this repo to src/packages/ and added the following to src/client/config.js:
```
  xterm: {
    ping: 10000
  }
```

I see the initial 101 to `/apps/Xterm/socket` accompanied by 
`Websocket::constructor() Xterm ws://os.chatsubo.local/apps/Xterm/socket`
in the console... but I'm not seeing any additional 101s.
I see that I can inspect the 101 and there's a "Messages" tab, where I see the ANSI terminal I//O, but I don't see any pings in the websocket messages or network tab.

![image](https://user-images.githubusercontent.com/2325870/83193205-9f227c80-a104-11ea-9b52-d9842165b226.png)

Testing without nginx I see the same thing (reducing moving parts)

**Comment by andersevenrud** [comment]
Hm. When you switched to a local git version instead of the npm one, did you checkout the branch (noted in PR) I made the changes in ?

Or if you did and it's still not working, here's a rundown on how it's usually done:

```
cd src/packages
git clone <repo>
cd <repo>
git checkout <branch>
npm install
npm run build
cd ../../..
npm run package:discover
```

**Comment by elixx** [comment]
Sheesh, I didn't catch the feature branch. Testing now...

**Comment by andersevenrud** [comment]
FYI: Any packages installed outside `node_modules` takes priority, so you don't have to uninstall the npm one :)

**Comment by elixx** [comment]
The socket opens, I see the terminal I/O messages (and the pings!) in the 101's messages tab, but the window only displays `Requesting connection...`. 

![image](https://user-images.githubusercontent.com/2325870/83194007-ef4e0e80-a105-11ea-9dcf-2ac0a35c4847.png)

Console shows:
![image](https://user-images.githubusercontent.com/2325870/83193901-c75eab00-a105-11ea-8295-e486db444a7a.png)

**Comment by andersevenrud** [comment]
First thing that comes to mind is that you didn't restart the server.

**Comment by elixx** [comment]
That did it :)

It works. And I can say with some confidence that all of the os.js components seem to work behind CloudFlare, now! Big ups!!

**Comment by andersevenrud** [comment]
Glad to hear it! I'll publish these changes now :)

**Comment by andersevenrud** [comment]
Aaaand it's out (as 1.3.0)! Thanks for the request and help with testing :blush: 

You can just nuke your `src/packages` repo and re-install the npm one, then run discovery and you should be back to your original state.

**Comment by andersevenrud** [comment]
> I hope to contribute in the future, but am somewhat green to Javascript. Been learning a lot about browser nuances!

If there's anything that you want to contribute to, just hit me up on email or gitter and I will do my best to assist you getting started. I'm open for doing code reviews and things like that if you're not very familiar with the language or the browser tech (thankfully this step is pretty easy nowadays because you have an intermediate step like babel to transpile code that work anywhere).
