### ISSUE TITLE
Delay in pty resize call

### ISSUE THREAD

**Issue by elixx** [os-js/osjs-xterm-application#19]
When spawning an Xterm specifying non-default dimensions, the underlying pty isn't aware of the size of the window.

![image](https://user-images.githubusercontent.com/2325870/83461031-c4c9c180-a435-11ea-9c2e-d45e585b8fdb.png)

I think the idea was to delay the resize call until after the underlying connection is established

**Comment by andersevenrud** [comment]
Maybe you could test this branch ?

https://github.com/os-js/osjs-xterm-application/pull/20

Just in case these changes were for nothing :blush:

**Comment by elixx** [comment]
It works perfectly :)

**Comment by andersevenrud** [comment]
Thanks for testing!

I published this now
