### ISSUE TITLE
bug on 'exit' command with xTerm

### ISSUE THREAD

**Issue by elvi7major** [os-js/osjs-xterm-application#21]
hello team,
i want to report a bug i found its not big issue but will enhance experience
the bug is when you type the command 'exit' to close the ssh session opened the xTerm will hangs for ever cause the connection is closed but the socket not 
also when you click on (exit) the red icon it will close the xTerm but not the ssh session
take a look at the pictures attached

FIX:
as a fix you can add exit in the event 'osClose' like this
```javascript
ws.on('close', () => {
    ws.send('exit')
    term.writeln('... Disconnected. Press any key to close terminal ...');
    closed = true;
    clearInterval(pinger);
  });
```
also maybe you should add a condition when send if its exit pass with it onClose event
i hope i made it clear if not just tell me i will explain more
![qq](https://user-images.githubusercontent.com/31170276/114247850-144e1780-998e-11eb-827b-b1270b90aa2b.png)
![dd](https://user-images.githubusercontent.com/31170276/114248003-76a71800-998e-11eb-9f9d-28a94d229642.png)
![ss](https://user-images.githubusercontent.com/31170276/114248015-7c9cf900-998e-11eb-997e-ef48f4cce4fd.png)

**Comment by andersevenrud** [comment]
Hello! And thank you very much for the bug report. I will investigate this and try your suggestions.

**Comment by andersevenrud** [comment]
I just tried this out, and I'm not sure if I understand you fully.

> also when you click on (exit) the red icon it will close the xTerm but not the ssh session

When I close a window (the red button), it does close my SSH connection successfully. I monitored my processes and this was before closing:

```
root         538  0.0  0.0   8964  2604 ?        Ss   Apr08   0:00 sshd: /usr/bin/sshd -D [listener] 0 of 10-100 startups
anders      2061  0.0  0.0   5952  1084 ?        Ss   Apr08   0:00 ssh-agent -s
anders    231648  0.1  0.0  12284  5712 pts/9    Ss+  01:02   0:00 ssh anders@localhost
root      231650  0.1  0.0  12408  8772 ?        Ss   01:02   0:00 sshd: anders [priv]
anders    231652  0.0  0.0  12408  4408 ?        S    01:02   0:00 sshd: anders@pts/10
```

and this was after:

```
root         538  0.0  0.0   8964  2604 ?        Ss   Apr08   0:00 sshd: /usr/bin/sshd -D [listener] 0 of 10-100 startups
anders      2061  0.0  0.0   5952  1084 ?        Ss   Apr08   0:00 ssh-agent -s
```

I also got this output from the OS.js server:

```
WebSocket connection closed
[Xterm] Closing terminal...
```

> the bug is when you type the command 'exit' to close the ssh session opened the xTerm will hangs for ever cause the connection is closed but the socket not

I notice that the window does not close when you type `exit`. I can fix this. But what do you mean by  "cause the connection is closed but the socket not" ?

**Comment by elvi7major** [comment]
> Hello! And thank you very much for the bug report. I will investigate this and try your suggestions.

thanks bro just let me know if i can help

**Comment by elvi7major** [comment]
> I just tried this out, and I'm not sure if I understand you fully.
> 
> > also when you click on (exit) the red icon it will close the xTerm but not the ssh session
> 
> When I close a window (the red button), it does close my SSH connection successfully. I monitored my processes and this was before closing:
> 
> ```
> root         538  0.0  0.0   8964  2604 ?        Ss   Apr08   0:00 sshd: /usr/bin/sshd -D [listener] 0 of 10-100 startups
> anders      2061  0.0  0.0   5952  1084 ?        Ss   Apr08   0:00 ssh-agent -s
> anders    231648  0.1  0.0  12284  5712 pts/9    Ss+  01:02   0:00 ssh anders@localhost
> root      231650  0.1  0.0  12408  8772 ?        Ss   01:02   0:00 sshd: anders [priv]
> anders    231652  0.0  0.0  12408  4408 ?        S    01:02   0:00 sshd: anders@pts/10
> ```
> 
> and this was after:
> 
> ```
> root         538  0.0  0.0   8964  2604 ?        Ss   Apr08   0:00 sshd: /usr/bin/sshd -D [listener] 0 of 10-100 startups
> anders      2061  0.0  0.0   5952  1084 ?        Ss   Apr08   0:00 ssh-agent -s
> ```
> 
> I also got this output from the OS.js server:
> 
> ```
> WebSocket connection closed
> [Xterm] Closing terminal...
> ```
> 
> > the bug is when you type the command 'exit' to close the ssh session opened the xTerm will hangs for ever cause the connection is closed but the socket not
> 
> I notice that the window does not close when you type `exit`. I can fix this. But what do you mean by "cause the connection is closed but the socket not" ?

i mean when you type 'exit' this will close the ssh session and show that the connection to host is closed
and i checked again and the socket is closed fine its just maybe some delay from my computer

yeah basically closing the window after exit is the fix for this issue

**Comment by andersevenrud** [comment]
I've published an update for this application that closes the window automatically if the session was closed without an error.

This should take care of this issue. If not, please re-open :)

**Comment by andersevenrud** [comment]
Please note that you have to restart your server after updating this application.
