### ISSUE TITLE
Copy/Paste does not work propertly

### ISSUE THREAD

**Issue by mikeblackstock** [os-js/osjs-xterm-application#9]
Seems like copy/paste does not work as intended, at least on certain platforms.

- [x] Add context menu ?
- [x] Check out xterm clipboard APIs
---

**Original message**

 FN-CTRL-RETURN to copy xterm text and FN-SHIFT-RETURN to paste works but when 'the pressure is on' it usually gets fouled up. Plus chromebooks don't have an FN key :(

**Comment by andersevenrud** [comment]
Thanks. I've updated the description and title of this issue, FYI :)

**Comment by andersevenrud** [comment]
Added a contextmenu that adds support for this. Should work in pretty much any modern browser.

Using this to get browser support: https://github.com/lgarron/clipboard-polyfill
